### ISSUE TITLE
新增`go`的`Instrumentation`翻译文件夹

### ISSUE THREAD

**Issue by Petrie** [open-telemetry/docs-cn#108]
新增文件夹 community/opentelemetryGoInstrumentation 存放go的Instrumentation的文档
原文地址：https://opentelemetry.io/docs/instrumentation/go/
- [ ] index.md https://github.com/open-telemetry/docs-cn/pull/117
- [ ] getting-started.md https://github.com/open-telemetry/docs-cn/pull/114
- [ ] libraries.md https://github.com/open-telemetry/docs-cn/pull/116
- [ ] manual.md https://github.com/open-telemetry/docs-cn/pull/115
- [ ] exporting_data.md https://github.com/open-telemetry/docs-cn/pull/113

**Comment by laziobird** [comment]
后面有go 中文翻译，可以再在 issue 上提交

**Comment by Petrie** [comment]
> 后面有go 中文翻译，可以再在 issue 上提交

好的，我会尽快更新上，这周日前出一版。

**Comment by Petrie** [comment]
这个工作比我想象中的多不少。 @laziobird  可能要下周才能提交了。   go的getting start有点详细的过分，有些句子还很长。 ￣□￣｜｜

**Comment by Petrie** [comment]
@addname @sunface @tensorchen @laziobird  PTAL , Thanks! ;)
