### ISSUE TITLE
完善 specification/logs 文件夹内文章翻译

### ISSUE THREAD

**Issue by noobone** [open-telemetry/docs-cn#111]
原文地址：https://opentelemetry.io/docs/reference/specification/logs/overview/
原文档仓库地址：https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/logs
翻译输出文件夹：https://github.com/open-telemetry/docs-cn/tree/main/specification/logs

- [ ] [README.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/README.md)
- [ ] [data-model.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md)
- [ ] [logging-library-sdk.md](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/logging-library-sdk.md)
- [ ] [semantic_conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/logs/semantic_conventions)

**Comment by svrnm** [comment]
> [!IMPORTANT]
> 此仓库已归档，将不再接受任何更新，包括不限于如：接受问题、拉取请求的处理。
>
> 若需获取有关 OpenTelemetry 文档及网站本地化方面的资料，可通过访问网址 [opentelemetry.io](https://github.com/open-telemetry/opentelemetry.io) 来查阅相关内容。
> 
> This repository is archived and will not receive any updates or accept issues or pull requests
>
> Localizations for the OpenTelemetry documentation and website are now part of the [website repository](https://github.com/open-telemetry/opentelemetry.io)
