### ISSUE TITLE
提案：项目结构的定义

### ISSUE THREAD

**Issue by wph95** [open-telemetry/docs-cn#35]
### 项目结构的定义

```
├── COMMUNITY-CN.md
├── CONTRIBUTING-CN.md
├── README.md
├── community
├── libs
│   └── java        
├── original             
│   ├── community         # https://github.com/open-telemetry/community
│   ├── specification     # https://github.com/open-telemetry/opentelemetry-specification
│   └── website           # Optional: https://github.com/open-telemetry/opentelemetry.io content/en
└── specification

```

#### original：

​	 使用 git submodule，作为原始英文文档，围绕其进行中文翻译。上游发布稳定版本后进行更新。

#### COMMUNITY-CN.md:

    用于记录和分析中文社区的文章与教程。

**Comment by WPH95** [comment]
个人建议：本项目的意义通过翻译官方文档的方式，帮助母语为中文的开发者更好的了解 OTel。虽然非常乐意和采纳非官方文档和教程，但在当前官方文档翻译较少的情况下，容易给初学者造成歧义。因此在 1.0.0-RC 前应当专注于 spec 和 website （如果可能）的翻译。对于非官方资源，由一个统一的文件进行展示。

**Comment by sunface** [comment]
嗯，有道理的。
因为他这个教程暂时没有替代品，对于新手蛮友好的，我先放在首页，标注为`非官方`，等未来再看看怎么统一处理

**Comment by martinliu** [comment]
大家好，我才开始关注这个项目。

我发现中文和日文拉了独立的 repo 做本地化，这样做很可能导致翻译成果无法直接通过官方文档网站上访问。这样我们的努力就大打折扣了。

我建议：最好能直接在官方文档库中做贡献，在这个目录 https://github.com/open-telemetry/opentelemetry.io/tree/main/content 中加一个 zh-cn 的目录。由于这个网站所使用的皮肤本来是支持中文语言的https://github.com/google/docsy/tree/master/i18n 因此这样做应该是可行的。K8s 社区的官方文档是直接在网站的 repo 里做的，并没有拉独立的 ropo， 那边的中国的小伙伴贡献的挺顺畅的。

建议这个 repo 主要用于大家的中文社区的讨论和交流。如果真正的翻译工作最好是，在和官方商量之后，从直接汉化官网的角度去做。好在大家目前的工作量还不是很大，及时的调整工作方式，优化结果产出，目前是最好的时候。

**Comment by JaredTan95** [comment]
> 大家好，我才开始关注这个项目。
> 
> 我发现中文和日文拉了独立的 repo 做本地化，这样做很可能导致翻译成果无法直接通过官方文档网站上访问。这样我们的努力就大打折扣了。
> 
> 我建议：最好能直接在官方文档库中做贡献，在这个目录 https://github.com/open-telemetry/opentelemetry.io/tree/main/content 中加一个 zh-cn 的目录。由于这个网站所使用的皮肤本来是支持中文语言的https://github.com/google/docsy/tree/master/i18n 因此这样做应该是可行的。K8s 社区的官方文档是直接在网站的 repo 里做的，并没有拉独立的 ropo， 那边的中国的小伙伴贡献的挺顺畅的。
> 
> 建议这个 repo 主要用于大家的中文社区的讨论和交流。如果真正的翻译工作最好是，在和官方商量之后，从直接汉化官网的角度去做。好在大家目前的工作量还不是很大，及时的调整工作方式，优化结果产出，目前是最好的时候。

同意，很多 CNCF 项目里面的国际化支持都是在官方统一切换支持的，比如 https://istio.io/latest/docs/ 与 https://istio.io/latest/zh/docs/, https://kubernetes.io/ 与 https://kubernetes.io/zh/ etc.

**Comment by laziobird** [comment]
> > 大家好，我才开始关注这个项目。
> > 我发现中文和日文拉了独立的 repo 做本地化，这样做很可能导致翻译成果无法直接通过官方文档网站上访问。这样我们的努力就大打折扣了。
> > 我建议：最好能直接在官方文档库中做贡献，在这个目录 https://github.com/open-telemetry/opentelemetry.io/tree/main/content 中加一个 zh-cn 的目录。由于这个网站所使用的皮肤本来是支持中文语言的https://github.com/google/docsy/tree/master/i18n 因此这样做应该是可行的。K8s 社区的官方文档是直接在网站的 repo 里做的，并没有拉独立的 ropo， 那边的中国的小伙伴贡献的挺顺畅的。
> > 建议这个 repo 主要用于大家的中文社区的讨论和交流。如果真正的翻译工作最好是，在和官方商量之后，从直接汉化官网的角度去做。好在大家目前的工作量还不是很大，及时的调整工作方式，优化结果产出，目前是最好的时候。
> 
> 同意，很多 CNCF 项目里面的国际化支持都是在官方统一切换支持的，比如 https://istio.io/latest/docs/ 与 https://istio.io/latest/zh/docs/, https://kubernetes.io/ 与 https://kubernetes.io/zh/ etc.

其实这是最好的方式，前提技术文档层面完善，齐整以后更合适。希望多贡献中文文档吧

**Comment by svrnm** [comment]
> [!IMPORTANT]
> 此仓库已归档，将不再接受任何更新，包括不限于如：接受问题、拉取请求的处理。
>
> 若需获取有关 OpenTelemetry 文档及网站本地化方面的资料，可通过访问网址 [opentelemetry.io](https://github.com/open-telemetry/opentelemetry.io) 来查阅相关内容。
> 
> This repository is archived and will not receive any updates or accept issues or pull requests
>
> Localizations for the OpenTelemetry documentation and website are now part of the [website repository](https://github.com/open-telemetry/opentelemetry.io)
