### ISSUE TITLE
是否需要统一特定单词的中文翻译

### ISSUE THREAD

**Issue by GlowingRuby** [open-telemetry/docs-cn#38]
telemetry，有时候翻译成遥测，有时候翻译成遥感
trace，是用追踪还是链路，还是直接用英文原文
类似的应该还有很多，我觉得我们需要统一下规范，避免读者阅读时的困惑甚至翻译时的困惑。

**Comment by liangyuanpeng** [comment]
我觉得专有名词用英文是最合适的，例如metrics一般中文文章都是叫metrics(当然也有些翻译为指标，但原单词最合适)

**Comment by dengliming** [comment]
确实，不过个人觉得telemetry还是翻译成遥测好点

**Comment by Superskyyy** [comment]
我也认为保留原单词比较好，不然在以后翻译出现不统一容易造成混乱。

**Comment by martinliu** [comment]
* telemetry 如果出现在技术术语/专用术语里，不应该做翻译；如果在主谓宾里出现了，翻译成 *遥测* 是目前比较普遍的。
* trace 同上，如果出现债主谓宾里，建议翻译成 *追踪*

是否需要统一特定单词的中文翻译？？
> 最好能开一个术语表的文件，所有译者都随时贡献和讨论需要进入这个清单中的词汇，[这里有一个例子可以参考一下](https://github.com/DevOps-Handbook/DevOps-Handbook.github.io/blob/master/glossary.md)。

一份统一的术语表有利于所有人的一致性，还可以让后来者更容易参与。

**Comment by svrnm** [comment]
> [!IMPORTANT]
> 此仓库已归档，将不再接受任何更新，包括不限于如：接受问题、拉取请求的处理。
>
> 若需获取有关 OpenTelemetry 文档及网站本地化方面的资料，可通过访问网址 [opentelemetry.io](https://github.com/open-telemetry/opentelemetry.io) 来查阅相关内容。
> 
> This repository is archived and will not receive any updates or accept issues or pull requests
>
> Localizations for the OpenTelemetry documentation and website are now part of the [website repository](https://github.com/open-telemetry/opentelemetry.io)
