### ISSUE TITLE
关于中英文混排的讨论

### ISSUE THREAD

**Issue by GlowingRuby** [open-telemetry/docs-cn#39]
我个人比较赞成这种方式
> 中文正文及标题中出现的英文及数字应该使用半角方式输入，并且在左右各留一个半角空格。如果这些这些半角英文及数字的左边或者右边紧接着任何的中文全角括号或者其他标点符号的话，则不需要加入半角空格。

**Comment by svrnm** [comment]
> [!IMPORTANT]
> 此仓库已归档，将不再接受任何更新，包括不限于如：接受问题、拉取请求的处理。
>
> 若需获取有关 OpenTelemetry 文档及网站本地化方面的资料，可通过访问网址 [opentelemetry.io](https://github.com/open-telemetry/opentelemetry.io) 来查阅相关内容。
> 
> This repository is archived and will not receive any updates or accept issues or pull requests
>
> Localizations for the OpenTelemetry documentation and website are now part of the [website repository](https://github.com/open-telemetry/opentelemetry.io)
