### ISSUE TITLE
增加opentelemetry-java-instrumentation项目的开发引导文档翻译

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/docs-cn#45]

**Comment by laziobird** [comment]
Hi，tydhot .
  对于opentelemetry 这块开发文档，可以翻译然后PR么？最近我们一直在研究和考虑实践到生产环境

**Comment by laziobird** [comment]
> _No description provided._

Hi，tydhot .
对于opentelemetry https://github.com/open-telemetry/opentelemetry-java-instrumentation ，也踩了些坑。
这块开发文档我想翻译PR，可以么？最近我们一直在研究和考虑实践到生产环境

**Comment by laziobird** [comment]
https://github.com/open-telemetry/docs-cn/tree/main/community/opentelemetryJavaInstrumentation 最新的翻译，还不太全
