### ISSUE TITLE
增加opentelemetry collector文档的翻译

### ISSUE THREAD

**Issue by tydhot** [open-telemetry/docs-cn#51]

**Comment by jordy1024** [comment]
Hi，tydhot；
`collector` 这部分，我想参与并贡献一下。是直接通过pr吗？

**Comment by tydhot** [comment]
@jordy1024 当然，目前应该没有正在进行的翻译计划，直接进行pr就行

**Comment by laziobird** [comment]
https://github.com/open-telemetry/docs-cn/blob/main/community/opentelemtryCollector/design.md
最新翻译更新
