### ISSUE TITLE
Request to participate in docs-cn maintenance

### ISSUE THREAD

**Issue by tensorchen** [open-telemetry/docs-cn#6]
Hi all,

I am a developer from China, and very happy to be a member of opentelemetry open-telemetry/community#346. I have been continuously monitoring the progress of opentelemetry, and also participated in the contributions of opentelemetry-rust, opentelemetry-go, used opentelemetry-collector in the company's business.

With more and more attention to opentelemetry in China, It would be great if there is a Chinese document.Concerned about the `docs-cn` repo. Can I be set up as a maintainer?  I am very willing to participate in maintenance, and look forward to attracting more Chinese community partners.

**Comment by SergeyKanzhelev** [comment]
ping us if no reply from the current maintainers.

**Comment by dengliming** [comment]
+1 @SergeyKanzhelev

**Comment by sunface** [comment]
@yurishkuro @SergeyKanzhelev He is a good and passionate  developer,please help us to deal with his application.

**Comment by sunface** [comment]
I'm going to close this issue, if anyone has any questions, feel free to re-open it.

**Comment by dengliming** [comment]
@sunface Can you also add me to maintainer team？I already file an issue here. [https://github.com/open-telemetry/community/issues/438](https://github.com/open-telemetry/community/issues/438) Thanks.

**Comment by sunface** [comment]
> @sunface Can you also add me to maintainer team？I already file an issue here. [open-telemetry/community#438](https://github.com/open-telemetry/community/issues/438) Thanks.

Sorry for the late reply, the answer is : I'm afraid not.
Because we have no plans to add new members to maintainer team at present. You can contribute to this repo first,  if everything goes well, we will invite you to maintainer team in the not far future.
