### ISSUE TITLE
增加 opentelemetry-js 的翻译

### ISSUE THREAD

**Issue by HessTina-YuI** [open-telemetry/docs-cn#69]

**Comment by svrnm** [comment]
> [!IMPORTANT]
> 此仓库已归档，将不再接受任何更新，包括不限于如：接受问题、拉取请求的处理。
>
> 若需获取有关 OpenTelemetry 文档及网站本地化方面的资料，可通过访问网址 [opentelemetry.io](https://github.com/open-telemetry/opentelemetry.io) 来查阅相关内容。
> 
> This repository is archived and will not receive any updates or accept issues or pull requests
>
> Localizations for the OpenTelemetry documentation and website are now part of the [website repository](https://github.com/open-telemetry/opentelemetry.io)
