### ISSUE TITLE
the link for "参与中文文档贡献" is 404 not found.

### ISSUE THREAD

**Issue by Duncan-tree-zhou** [open-telemetry/docs-cn#72]
in [docs-cn/specification/Readme.md](https://github.com/open-telemetry/docs-cn/blob/main/specification/Readme.md) , the link `https://gitter.im/open-telemetry/docs-cn` for "参与中文文档贡献" is 404 not found in gitter. should we fix the link or disable the link ?

**Comment by laziobird** [comment]
![image](https://user-images.githubusercontent.com/16099500/147312432-8cc1ab2c-b1cb-41c2-a017-f46f2f573b78.png)
Me too.  OpenTelemetry is very helpful for observability. 
So, I recently research it deeply and would like to translated some contents into Chinese .
